import Head from 'next/head';
import Recommended from '@/components/layouts/recommended/Recommended';
import NewPost from '@/components/posts/NewPost';
import PostsList from '@/components/posts/PostsList';
import { useEffect } from 'react';
import { postStore } from '@/store';

function Home() {
    const { fetchPosts } = postStore();

    useEffect(() => {
        console.log('Home');
        fetchPosts();
    }, []);

    return (
        <div className="Home">
            <Head>
                <title>Waeve - Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-grow">
                <div className="w-full space-y-4">
                    <NewPost />
                    <PostsList />
                </div>
                <div className="hidden md:block ml-4">
                    <Recommended />
                </div>
            </div>
        </div>
    );
}
export default Home;
