import React from 'react';
import Head from 'next/head';

function Explore() {
    return (
        <div className="Settings">
            <Head>
                <title>Waeve - Settings</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Explore</h1>
        </div>
    );
}

export default Explore;
